version: '3'

services:
  handler:
    build:
      context: handler
      dockerfile: Dockerfile
    depends_on:
      - journal
      - feeding_calc
    ports:
      - "5000:8000"
  journal:
    build:
      context: journal
      dockerfile: Dockerfile
    ports:
      - "5001:8000"
  feeding_calc:
    build:
      context: feeding_calc
      dockerfile: Dockerfile
    ports:
      - "5002:8000"
