version: '3'

services:
  handler:
    build:
      context: handler
      dockerfile: Dockerfile
    command: ["gunicorn", "--bind", ":8000", "--reload", "handler.wsgi:app"]
    depends_on:
      - journal
      - feeding_calc
    ports:
      - "${HANDLER_PORT}:8000"
    volumes:
      - ./handler:/app/handler
  journal:
    build:
      context: journal
      dockerfile: Dockerfile
    command: [ "gunicorn", "--bind", ":8000", "--reload", "journal.wsgi:app" ]
    ports:
      - "${JOURNAL_PORT}:8000"
    volumes:
      - ./journal:/app/journal
  feeding_calc:
    build:
      context: feeding_calc
      dockerfile: Dockerfile
    command: [ "gunicorn", "--bind", ":8000", "--reload", "feeding_calc.wsgi:app" ]
    ports:
      - "${FEEDING_CALC_PORT}:8000"
    volumes:
      - ./feeding_calc:/app/feeding_calc
  temperature:
    build:
      context: temperature
      dockerfile: Dockerfile
    command: [ "gunicorn", "--bind", ":8000", "--reload", "temperature.wsgi:app" ]
    ports:
      - "${TEMPERATURE_PORT}:8000"
    volumes:
      - ./temperature:/app/temperature

