version: '3'

services:
  handler:
    build:
      context: handler
      dockerfile: Dockerfile
    depends_on:
      - journal
      - feeding_calc
    ports:
      - "${HANDLER_PORT}:8000"
    environment:
      - SERVER_URL
      - HANDLER_PORT
      - FEEDING_CALC_PORT
      - JOURNAL_PORT
  journal:
    build:
      context: journal
      dockerfile: Dockerfile
    ports:
      - "${JOURNAL_PORT}:8000"
    environment:
      - SERVER_URL
      - HANDLER_PORT
      - FEEDING_CALC_PORT
      - JOURNAL_PORT
  feeding_calc:
    build:
      context: feeding_calc
      dockerfile: Dockerfile
    ports:
      - "${FEEDING_CALC_PORT}:8000"
    environment:
      - SERVER_URL
      - HANDLER_PORT
      - FEEDING_CALC_PORT
      - JOURNAL_PORT
