version: '3'

services:
  handler:
    build:
      context: handler
      dockerfile: Dockerfile
    command: ["gunicorn", "--bind", ":8000", "--reload", "handler.wsgi:app"]
    depends_on:
      - journal
      - feeding_calc
    ports:
      - "5000:8000"
    volumes:
      - ./handler:/app/handler
  journal:
    build:
      context: journal
      dockerfile: Dockerfile
    command: [ "gunicorn", "--bind", ":8000", "--reload", "journal.wsgi:app" ]
    ports:
      - "${JOURNAL_PORT}:8000"
    volumes:
      - ./journal:/app/journal
  journal_db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
  feeding_calc:
    build:
      context: feeding_calc
      dockerfile: Dockerfile
    command: [ "gunicorn", "--bind", ":8000", "--reload", "feeding_calc.wsgi:app" ]
    ports:
      - "${FEEDING_CALC_PORT}:8000"
    volumes:
      - ./feeding_calc:/app/feeding_calc
  feeding_calc_db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
