version: '3'

services:
  handler:
    build:
      context: handler
      dockerfile: Dockerfile
    command: ["gunicorn", "--bind", ":8000", "--reload", "--preload",  "handler.wsgi:app"]
    depends_on:
      - journal
      - feeding_calc
    ports:
      - "${HANDLER_PORT}:8000"
    volumes:
      - ./handler:/app/handler
      - ./config.yml:/app/config.yml
  journal:
    build:
      context: journal
      dockerfile: Dockerfile
    command: [ "gunicorn", "--bind", ":8000", "--reload", "--preload",  "journal.wsgi:app" ]
    ports:
      - "${JOURNAL_PORT}:8000"
    volumes:
      - ./journal:/app/journal
      - ./config.yml:/app/config.yml
  feeding_calc:
    build:
      context: feeding_calc
      dockerfile: Dockerfile
    command: [ "gunicorn", "--bind", ":8000", "--reload", "--preload",  "feeding_calc.wsgi:app" ]
    ports:
      - "${FEEDING_CALC_PORT}:8000"
    volumes:
      - ./feeding_calc:/app/feeding_calc
      - ./config.yml:/app/config.yml
  temperature:
    build:
      context: temperature
      dockerfile: Dockerfile
    command: [ "gunicorn", "--bind", ":8000", "--reload", "--preload",  "temperature.wsgi:app" ]
    ports:
      - "${TEMPERATURE_PORT}:8000"
    volumes:
      - ./temperature:/app/temperature
      - ./config.yml:/app/config.yml
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    command: [ "gunicorn", "--bind", ":8000", "--reload", "--preload", "frontend.wsgi:app" ]
    ports:
      - "${FRONTEND_PORT}:8000"
    volumes:
      - ./frontend:/app/frontend
      - ./config.yml:/app/config.yml
  nginx:
    build: ./nginx
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - handler
      - temperature
  temperature_db:
    image: postgres
    restart: always
    ports:
      - 5454:5454
    environment:
      - "${NGINX_PORT}:80"
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pair
      - POSTGRES_PORT=5454
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./nginx/nginx.conf:/app/nginx.conf

volumes:
  postgres_data:
